# Generated by Django 4.2.13 on 2024-06-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("sex", models.CharField(blank=True, max_length=10, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("google_sheet_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
