# Generated by Django 4.2.13 on 2024-06-26 11:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patients",
            name="google_sheet_url",
        ),
        migrations.AddField(
            model_name="patients",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+91", max_length=128, region=None
            ),
        ),
    ]
