# Generated by Django 4.2.13 on 2024-06-26 12:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_remove_patients_google_sheet_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+91", max_length=128, region=None
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=100, null=True
                    ),
                ),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("address", models.TextField(blank=True, default="", null=True)),
                ("age", models.PositiveIntegerField(default=18)),
                ("sex", models.CharField(default="other", max_length=10)),
                ("marital_status", models.CharField(default="single", max_length=20)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default="",
                        max_digits=7,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default="",
                        max_digits=7,
                        null=True,
                        verbose_name="Height (cm)",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=5,
                        null=True,
                        verbose_name="Blood Group",
                    ),
                ),
                ("purpose", models.TextField(blank=True, default="", null=True)),
                ("medical_issue", models.TextField(blank=True, default="", null=True)),
                ("medicine", models.TextField(blank=True, default="", null=True)),
                ("supplement", models.TextField(blank=True, default="", null=True)),
                (
                    "wake_up_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sleep_time", models.CharField(blank=True, max_length=100, null=True)),
                ("noon_nap", models.CharField(blank=True, max_length=100, null=True)),
                ("family_history", models.TextField(blank=True, default="", null=True)),
                ("veg", models.BooleanField(default=False)),
                ("non_veg", models.BooleanField(default=False)),
                ("jain", models.BooleanField(default=False)),
                ("egg", models.BooleanField(default=False)),
                ("chicken", models.BooleanField(default=False)),
                ("sea_food", models.BooleanField(default=False)),
                ("sweet", models.BooleanField(default=False)),
                ("spicy", models.BooleanField(default=False)),
                ("sour", models.BooleanField(default=False)),
                ("salty", models.BooleanField(default=False)),
                ("blend", models.BooleanField(default=False)),
                ("pungeant", models.BooleanField(default=False)),
                ("food_allergy", models.TextField(blank=True, default="", null=True)),
                (
                    "water_intake",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("beverage", models.TextField(blank=True, default="", null=True)),
                (
                    "outside_food",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("dessert", models.TextField(blank=True, default="", null=True)),
                ("fruits", models.TextField(blank=True, default="", null=True)),
                (
                    "alcohol",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "smoke",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("excercise", models.TextField(blank=True, default="", null=True)),
                ("time_excercise", models.TextField(blank=True, default="", null=True)),
                ("what_excercise", models.TextField(blank=True, default="", null=True)),
                ("day_excercise", models.TextField(blank=True, default="", null=True)),
                ("hair_problem", models.TextField(blank=True, default="", null=True)),
                ("hair_qaulity", models.TextField(blank=True, default="", null=True)),
                ("skin_quality", models.TextField(blank=True, default="", null=True)),
                ("diabetes", models.BooleanField(default=False)),
                ("thyroid", models.BooleanField(default=False)),
                ("pcos", models.BooleanField(default=False)),
                ("hypertension", models.BooleanField(default=False)),
                ("heart_disease", models.BooleanField(default=False)),
                ("cholesterol", models.BooleanField(default=False)),
                ("constipation", models.BooleanField(default=False)),
                ("diarrhea", models.BooleanField(default=False)),
                ("acidity", models.BooleanField(default=False)),
                ("head_ache", models.BooleanField(default=False)),
                ("body_pain", models.BooleanField(default=False)),
                ("irregular_period", models.BooleanField(default=False)),
                ("how_irrugular", models.TextField(blank=True, default="", null=True)),
                ("kids", models.BooleanField(default=False)),
                ("how_dilevery", models.TextField(blank=True, default="", null=True)),
                ("consume_oil", models.TextField(blank=True, default="", null=True)),
                ("consume_ghee", models.TextField(blank=True, default="", null=True)),
                ("consume_salt", models.TextField(blank=True, default="", null=True)),
                ("consume_sugar", models.TextField(blank=True, default="", null=True)),
                ("consume_milk", models.TextField(blank=True, default="", null=True)),
                ("consume_rice", models.TextField(blank=True, default="", null=True)),
                ("consume_flour", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Patients",
        ),
    ]
