# Generated by Django 4.2.13 on 2024-06-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_patient_delete_patients"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.FloatField(verbose_name="Height (m)")),
                ("weight", models.FloatField(verbose_name="Weight (kg)")),
                ("body_fat", models.FloatField(verbose_name="Body Fat (%)")),
                ("age", models.PositiveIntegerField(verbose_name="Age")),
                ("BMI", models.FloatField(verbose_name="Body Mass Index")),
                (
                    "RMR",
                    models.FloatField(verbose_name="Resting Metabolic Rate (kcal/day)"),
                ),
                (
                    "visceral_fat",
                    models.PositiveIntegerField(verbose_name="Visceral Fat"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="patient",
            name="day_excercise",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Days of Exercise"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="food_allergy",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Food Allergy"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="outside_food",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Outside food",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="time_excercise",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Time of Exercise"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="what_excercise",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Type of Exercise"
            ),
        ),
        migrations.CreateModel(
            name="session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_notes", models.TextField(blank=True, default="", null=True)),
                ("session_date", models.DateField()),
                ("start_meal_line", models.PositiveIntegerField()),
                ("end_meal_line", models.PositiveIntegerField()),
                (
                    "body_composition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manager.bodycomposition",
                    ),
                ),
            ],
        ),
    ]
