# Generated by Django 4.2.13 on 2024-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0010_alter_patient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
