# Generated by Django 4.2.13 on 2024-07-10 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0012_form_entry_alter_bodycomposition_height"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form_entry",
            old_name="messsage",
            new_name="message",
        ),
    ]
